//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzure.Acs.Oauth2.Client.WinRT {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAzure.Acs.Oauth2.Client.WinRT.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3707: The value &apos;{0}&apos; is not a valid OAuth grant_type..
        /// </summary>
        internal static string ID3707 {
            get {
                return ResourceManager.GetString("ID3707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3708: Access token request should have a valid value specified for the grant_type, client_id and client_secret..
        /// </summary>
        internal static string ID3708 {
            get {
                return ResourceManager.GetString("ID3708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3709: The value &apos;{0}&apos; is not a well-formed Uri..
        /// </summary>
        internal static string ID3709 {
            get {
                return ResourceManager.GetString("ID3709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3710: Access token request with authorization code should have a valid code and redirect_uri parameters specified..
        /// </summary>
        internal static string ID3710 {
            get {
                return ResourceManager.GetString("ID3710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3711: Access token response message should contain a valid access_token specified..
        /// </summary>
        internal static string ID3711 {
            get {
                return ResourceManager.GetString("ID3711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3712: The parameter &apos;expires_in&apos; should be an integer that gives the number of seconds the access token is valid..
        /// </summary>
        internal static string ID3712 {
            get {
                return ResourceManager.GetString("ID3712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3713: The parameter &apos;error_description&apos; cannot be set to an empty string..
        /// </summary>
        internal static string ID3713 {
            get {
                return ResourceManager.GetString("ID3713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3714: The parameter &apos;error_uri&apos; should be set to an Absolute Uri..
        /// </summary>
        internal static string ID3714 {
            get {
                return ResourceManager.GetString("ID3714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3715: Error response message should have the &apos;error&apos; parameter set to a valid value..
        /// </summary>
        internal static string ID3715 {
            get {
                return ResourceManager.GetString("ID3715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3716: EndUser authorization request requires the &apos;response_type&apos;, &apos;client_id&apos; and &apos;redirect_uri&apos; to be specified..
        /// </summary>
        internal static string ID3716 {
            get {
                return ResourceManager.GetString("ID3716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3717: The value &apos;{0}&apos; is not a valid OAuth &apos;response_type&apos;..
        /// </summary>
        internal static string ID3717 {
            get {
                return ResourceManager.GetString("ID3717", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3718: EndUser authorization response message should either have the &apos;code&apos; or the &apos;access_token&apos; parameter specified..
        /// </summary>
        internal static string ID3718 {
            get {
                return ResourceManager.GetString("ID3718", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3719: The parameter &apos;scope&apos; cannot be set to an empty string..
        /// </summary>
        internal static string ID3719 {
            get {
                return ResourceManager.GetString("ID3719", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3720: The parameter &apos;state&apos; cannot be set to an empty string..
        /// </summary>
        internal static string ID3720 {
            get {
                return ResourceManager.GetString("ID3720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3721: The HTTP method &apos;{0}&apos; and HTTP Content type &apos;{1}&apos; is not a supported combination..
        /// </summary>
        internal static string ID3721 {
            get {
                return ResourceManager.GetString("ID3721", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3722: The HTTP method &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ID3722 {
            get {
                return ResourceManager.GetString("ID3722", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3723: Unable to construct a valid OAuth message from the given set of parameters..
        /// </summary>
        internal static string ID3723 {
            get {
                return ResourceManager.GetString("ID3723", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3724: Cannot serialize the OAuth message of type &apos;{0}&apos;..
        /// </summary>
        internal static string ID3724 {
            get {
                return ResourceManager.GetString("ID3724", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3730: An invalid OAuth message was received..
        /// </summary>
        internal static string ID3730 {
            get {
                return ResourceManager.GetString("ID3730", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3731: An error occurred while reading or writing an OAuth message..
        /// </summary>
        internal static string ID3731 {
            get {
                return ResourceManager.GetString("ID3731", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3741: Authentication type &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ID3741 {
            get {
                return ResourceManager.GetString("ID3741", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3750: The redirect_uri does not match the Uri registered with the current client_id..
        /// </summary>
        internal static string ID3750 {
            get {
                return ResourceManager.GetString("ID3750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3751: The client_id could not be verified..
        /// </summary>
        internal static string ID3751 {
            get {
                return ResourceManager.GetString("ID3751", resourceCulture);
            }
        }
    }
}
